### ISSUE TITLE
Choosing Headings, missing comma in Line 20. All type is rendered in Lora.

### ISSUE THREAD

**Issue by wyatt-morris** [visualgui/prowebtype#2]
I noticed the headings were not rendered in Oswald as specified. The comma is missing between Oswald and sans-serif. Currently the code looks like this:

``` (CSS)
h1, h2, h3, h4, h5, h6 {font-family: 'Oswald' sans-serif; line-height: 1.1; margin: .8em 0 .3em 0;}
```

**Comment by visualgui** [comment]
Updated. Thanks.
